### ISSUE TITLE
Instalation issue os x / go 1.4.2

### ISSUE THREAD

**Issue by awrelll** [jbenet/ipfs#49]
Iancus-MacBook-Pro:~ aurel$ go get -u github.com/jbenet/go-ipfs/cmd/ipfs
Iancus-MacBook-Pro:~ aurel$ ipfs version
-bash: ipfs: command not found

**Comment by jbenet** [comment]
Looks like there's something wrong with your `$GOPATH`, or you haven't added your `$GOPATH`'s `/bin` to your `$PATH`. See the `GOPATH` section in this doc page: https://golang.org/doc/code.html#GOPATH

This repo is for the ipfs papers and spec. Please use github.com/jbenet/go-ipfs or our irc channel for help with the Go implementation.
