### ISSUE TITLE
Getting Started curl links are broken, need gateway.ipfs.io

### ISSUE THREAD

**Issue by tv42** [jbenet/ipfs#52]
http://ipfs.io/docs/getting-started/ says

```console
> curl "http://ipfs.io/ipfs/$hash"
```

needs to say

```console
> curl "http://gateway.ipfs.io/ipfs/$hash"
```

**Comment by jbenet** [comment]
Awesome, thanks! Yeah-- we meant to move the gateway to ipfs.io -- i've moved this to https://github.com/jbenet/ipfs-website/issues/3
